import { Container, Header, ThemeControl } from "@/components/index";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: {
		default: "The blog - Blog with Next.js",
		template: "%s | The Blog",
	},
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html
			lang="en"
			className="light">
			<body className="bg-slate-200">
				<Container>
					<ThemeControl />
					<Header />
					{children}
					<Footer />
				</Container>
			</body>
		</html>
	);
}
